plugins {
    id "com.android.application"
}

android {
    namespace "com.xpmini.fichero"
    compileSdk 35

    defaultConfig {
        applicationId "com.xpmini.fichero"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    packaging {
        resources {
            excludes += ["/META-INF/{AL2.0,LGPL2.1}"]
        }
    }
}
